RA-1910, configure paper ID column in search patients table
openmrs/openmrs-module-registrationapp pull request #109
Opened 2021-04-13 19:47 UTC by cioan

2021-04-13 19:47 UTC, cioan commented
@mogoodrich , this is the UHM-5273 ticket. Thanks!

2021-04-13 21:27 UTC, mogoodrich requested changes
Added a few review comments, thanks @cioan !

2021-04-13 21:27 UTC, mogoodrich commented on omod/src/main/java/org/openmrs/module/registrationapp/page/controller/FindPatientPageController.java
> +            // add the paper record identifier, if the definition is available (provided by the paper record module)
let's change this to "if a definition is available (the default is provided by  the paper record module)

2021-04-13 21:27 UTC, mogoodrich commented on omod/src/main/resources/config.xml
> +		<description>
for backwards compatibility, the default value here should be the one that is currently used ""paperrecord.patientDataDefinition.paperRecordIdentifier"

2021-04-13 21:27 UTC, mogoodrich commented on omod/src/main/resources/config.xml
> +			Paper record identifier definition
how about: Report Definition to retrieve the paper record identifier for a patient; default comes from paper record module

2021-04-13 22:24 UTC, mseaton commented
@cioan I agree with @mogoodrich .  The reason we took this approach was for backwards compatibility - we want things to work exactly like they currently do if someone upgrades (i.e. the fact that a new global property exists should be transparent, and all of the definition names should default to what they were hard-coded to before).

2021-04-14 18:53 UTC, mogoodrich approved these changes
LGTM, thanks @cioan !

2021-04-14 18:59 UTC, merged